{"title": "#hero"}
{"title": "#about"}
{"title": "#resume"}
{"title": "#portfolio"}
{"title": "#contact"}
{"title": "https://twitter.com/Amirhamidi2001/"}
{"title": "https://www.instagram.com/amirhamidi_official/"}
{"title": "https://t.me/Amirhamidi2001/"}
{"title": "https://www.facebook.com/amirhamidi2001/"}
{"title": "https://www.linkedin.com/in/amir-hamidi-18a815233/"}
{"title": "/static/static/img/portfolio/portfolio-1.jpg"}
{"title": "https://dentacaree.pythonanywhere.com"}
{"title": "/static/static/img/portfolio/portfolio-2.jpg"}
{"title": "https://imperial.pythonanywhere.com"}
{"title": "/static/static/img/portfolio/portfolio-3.jpg"}
{"title": "https://modernaa.pythonanywhere.com"}
{"title": "/static/static/img/portfolio/portfolio-4.jpg"}
{"title": "https://amirstore.pythonanywhere.com"}
{"title": "/static/static/img/portfolio/portfolio-5.jpg"}
{"title": "https://archiark.pythonanywhere.com"}
{"title": "/static/static/img/portfolio/portfolio-6.jpg"}
{"title": "https://karmastore.pythonanywhere.com"}
{"title": "/static/static/img/portfolio/portfolio-7.jpg"}
{"title": "https://medicioa.pythonanywhere.com"}
{"title": "https://twitter.com/Amirhamidi2001/"}
{"title": "https://www.instagram.com/amirhamidi_official/"}
{"title": "https://t.me/Amirhamidi2001/"}
{"title": "https://www.facebook.com/amirhamidi2001/"}
{"title": "https://www.linkedin.com/in/amir-hamidi-18a815233/"}
{"title": "https://github.com/Amirhamidi2001/"}
{"title": "https://amirhamidi.pythonanywhere.com/"}
{"title": "https://bootstrapmade.com/"}
{"title": "#"}
